server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chengcd/spring-config.git
          username: chengcd
          password: 1qaz!QAZ1
          searchPaths: my-sample-config